###

POST http://127.0.0.1:8000/token

###
GET  http://127.0.0.1:8000/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwicGFzc3dvcmQiOiJwYXNzd29yZDEyMyIsImV4cCI6MTczMjc5NDkzN30.8IJUnLngcmQH3tHoPazAz7BFiC_4XAwzNBO8xVstSBQ

###
GET http://127.0.0.1:8000/

