
###
GET http://127.0.0.1:8000/products
Content-Type: application/json

###
GET http://127.0.0.1:8000/product/2
Content-Type: application/json

###
POST http://127.0.0.1:8000/product
Content-Type: application/json

{
  "name": "sepatu",
  "description": "iki sepatu anyar",
  "price": 200.00,
  "quantity": 20
}

###
PUT http://127.0.0.1:8000/product/2
Content-Type: application/json

{
  "name": "sepatu update",
  "description": "iki sepatu anyar tenan",
  "price": 200.00,
  "quantity": 20
}

###
DELETE http://127.0.0.1:8000/product/2
Content-Type: application/json

