@url = http://127.0.0.1:8000
@path = products

###
GET {{url}}/{{path}}
Content-Type: application/json

###
GET {{url}}/{{path}}/3
Content-Type: application/json

###
POST {{url}}/{{path}}
Content-Type: application/json

{
  "name": "sepatu new data",
  "description": "iki sepatu anyar",
  "price": 200.00,
  "quantity": 20,
  "id_user": 1
}

###
PUT {{url}}/{{path}}/3
Content-Type: application/json

{
  "name": "sepatu update 2xxxx",
  "description": "iki sepatu anyar tenan",
  "price": 200.00,
  "quantity": 20
}

###
DELETE {{url}}/{{path}}/3
Content-Type: application/json

