@url = http://127.0.0.1:8000
@path = products

###
GET {{url}}/{{path}}
Content-Type: application/json

###
GET {{url}}/{{path}}/3
Content-Type: application/json

###
POST {{url}}/{{path}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjA4MTIzNDUxMjM0NSIsImFkZHJlc3MiOiJqbC4gc3VwYXJ0bWFuIiwiaWQiOjEzLCJuYW1lIjoidXNlcjYiLCJlbWFpbCI6InVzZXI2QGdtYWlsLmNvbSIsImV4cCI6MTczMjg3MzgwMn0.U2dPO8sPGctFHfeO93d7mQfIOv9bAQxPLzCGip-jm88

{
  "name": "sepatu new data",
  "description": "iki sepatu anyar",
  "price": 200.00,
  "quantity": 20
}

###
PUT {{url}}/{{path}}/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjA4MTIzNDUxMjM0NSIsImFkZHJlc3MiOiJqbC4gc3VwYXJ0bWFuIiwiaWQiOjEzLCJuYW1lIjoidXNlcjYiLCJlbWFpbCI6InVzZXI2QGdtYWlsLmNvbSIsImV4cCI6MTczMjg3MzgwMn0.U2dPO8sPGctFHfeO93d7mQfIOv9bAQxPLzCGip-jm88

{
  "name": "sepatu update 2xxxx",
  "description": "iki sepatu anyar tenan",
  "price": 200.00,
  "quantity": 20
}

###
DELETE {{url}}/{{path}}/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5hbWUiOiJ1c2VyNiIsInBob25lIjoiMDgxMjM0NTEyMzQ1IiwiZW1haWwiOiJ1c2VyNkBnbWFpbC5jb20iLCJhZGRyZXNzIjoiamwuIHN1cGFydG1hbiIsImV4cCI6MTczMjg3NDY3N30.QDE05sXv8tWPD1J7RjD9t8wXmY5VXNzTyB9H-6WgZbk


