# SECRET_KEY='secret'
JWT_SECRET_ACCESS_KEY='LhVjhTZNl9V4LhSYmlQkeB1m3As3+TUkmoMa1G5Eq+U='
JWT_SECRET_REFRESH_KEY='eOW45FYqZgPFSLDQzJ9X6GPJ+cp5s9yj8zTAqFix7UA='
JWT_ALGORITHM = 'HS256'
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_Day = 30
DATABASE_URL = "mysql+aiomysql://root:@localhost:3306/mydatabase"
# DATABASE_URL = "sqlite:///./test.db"
