@url = http://127.0.0.1:8000
@path = auth

###
POST {{url}}/{{path}}/login
Content-Type: application/json

{
  "email": "user6@gmail.com",
  "password": "12345678"
}

###
POST {{url}}/{{path}}/register
Content-Type: application/json

{
  "name": "user1",
  "email": "user1@gmail.com",
  "phone": "081234512345",
  "address": "jl. superman",
  "password": "12345678"
}


###
POST {{url}}/{{path}}/check
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjYiLCJpZCI6MTcsImFkZHJlc3MiOiJqbC4gc3VwYXJ0bWFuIiwiZW1haWwiOiJ1c2VyNkBnbWFpbC5jb20iLCJwaG9uZSI6IjA4MTIzNDUxMjM0NSIsInJvbGUiOiJVU0VSIiwiZXhwIjoxNzM4NjU5MTQzfQ.fMZ6sy0viApRJj3gvYhOEg0CZN452XZGoO_8eO_KikI

